use std::fs::{self, OpenOptions};
use std::io::{ErrorKind, Write};
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use uuid::{Uuid, Version};

use crate::error::{AppError, AppResult};

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
struct StoredHwid {
    #[serde(default)]
    auto: Option<Uuid>,
    #[serde(default)]
    custom: Option<Uuid>,
}

#[derive(Debug, Clone, Serialize, PartialEq, Eq)]
pub struct HwidDescription {
    /// The value sent in X-HWID on the next subscription request.
    pub effective: Uuid,
    /// The per-install UUID generated by Cloakwire.
    pub auto: Option<Uuid>,
    /// An optional user-pinned UUID copied from another device.
    pub custom: Option<Uuid>,
}

#[derive(Debug, Clone)]
pub struct HwidStore {
    path: PathBuf,
}

impl HwidStore {
    pub fn new(path: PathBuf) -> Self {
        Self { path }
    }

    pub fn get_or_create(&self) -> AppResult<Uuid> {
        let mut stored = self.read_or_default()?;
        if let Some(custom) = stored.custom {
            return Ok(custom);
        }
        if let Some(auto) = stored.auto {
            return Ok(auto);
        }

        let auto = Uuid::new_v4();
        stored.auto = Some(auto);
        self.write_atomic(&stored)?;
        Ok(auto)
    }

    /// Rotates only the automatically generated identity. A custom override is
    /// deliberately preserved and remains the effective value until cleared.
    pub fn reset(&self) -> AppResult<Uuid> {
        let mut stored = self.read_or_default()?;
        let auto = Uuid::new_v4();
        stored.auto = Some(auto);
        self.write_atomic(&stored)?;
        Ok(auto)
    }

    pub fn set_custom(&self, value: Option<Uuid>) -> AppResult<()> {
        if let Some(uuid) = value {
            validate_v4(uuid, "custom HWID")?;
        }
        let mut stored = self.read_or_default()?;
        if stored.auto.is_none() {
            stored.auto = Some(Uuid::new_v4());
        }
        stored.custom = value;
        self.write_atomic(&stored)
    }

    pub fn describe(&self) -> AppResult<HwidDescription> {
        let effective = self.get_or_create()?;
        let stored = self.read_or_default()?;
        Ok(HwidDescription {
            effective,
            auto: stored.auto,
            custom: stored.custom,
        })
    }

    fn read_or_default(&self) -> AppResult<StoredHwid> {
        match fs::read_to_string(&self.path) {
            Ok(value) => parse_stored(&value),
            Err(error) if error.kind() == ErrorKind::NotFound => Ok(StoredHwid::default()),
            Err(error) => Err(error.into()),
        }
    }

    #[cfg(test)]
    fn reset_with_replace<F>(&self, replace: F) -> AppResult<Uuid>
    where
        F: FnOnce(&Path, &Path) -> std::io::Result<()>,
    {
        let mut stored = self.read_or_default()?;
        let auto = Uuid::new_v4();
        stored.auto = Some(auto);
        self.write_atomic_with(&stored, replace)?;
        Ok(auto)
    }

    fn write_atomic(&self, stored: &StoredHwid) -> AppResult<()> {
        self.write_atomic_with(stored, |temporary_path, target_path| {
            fs::rename(temporary_path, target_path)
        })
    }

    fn write_atomic_with<F>(&self, stored: &StoredHwid, replace: F) -> AppResult<()>
    where
        F: FnOnce(&Path, &Path) -> std::io::Result<()>,
    {
        ensure_parent(&self.path)?;
        let temporary_path = temporary_path(&self.path)?;
        let result = (|| -> AppResult<()> {
            let body = serde_json::to_vec(stored)
                .map_err(|_| AppError::Validation("HWID persistence failed".into()))?;
            let mut file = OpenOptions::new()
                .write(true)
                .create_new(true)
                .open(&temporary_path)?;
            file.write_all(&body)?;
            file.flush()?;
            file.sync_all()?;
            drop(file);
            replace(&temporary_path, &self.path)?;
            Ok(())
        })();

        if result.is_err() {
            let _ = fs::remove_file(&temporary_path);
        }
        result
    }
}

fn parse_stored(value: &str) -> AppResult<StoredHwid> {
    let trimmed = value.trim();
    if trimmed.is_empty() {
        return Err(AppError::Validation("stored HWID is empty".into()));
    }

    // Desktop releases before custom overrides stored one raw UUID. Preserve it
    // as the auto identity and migrate to JSON only on the next write.
    if !trimmed.starts_with('{') {
        let auto = parse_v4(trimmed, "stored HWID")?;
        return Ok(StoredHwid {
            auto: Some(auto),
            custom: None,
        });
    }

    let stored: StoredHwid = serde_json::from_str(trimmed)
        .map_err(|_| AppError::Validation("stored HWID data is invalid".into()))?;
    if let Some(auto) = stored.auto {
        validate_v4(auto, "stored automatic HWID")?;
    }
    if let Some(custom) = stored.custom {
        validate_v4(custom, "stored custom HWID")?;
    }
    Ok(stored)
}

fn parse_v4(value: &str, label: &str) -> AppResult<Uuid> {
    let uuid = Uuid::parse_str(value)
        .map_err(|_| AppError::Validation(format!("{label} is not a valid UUID")))?;
    validate_v4(uuid, label)?;
    Ok(uuid)
}

fn validate_v4(uuid: Uuid, label: &str) -> AppResult<()> {
    if uuid.get_version() != Some(Version::Random) {
        return Err(AppError::Validation(format!(
            "{label} must be a random UUID v4"
        )));
    }
    Ok(())
}

fn ensure_parent(path: &Path) -> AppResult<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    Ok(())
}

fn temporary_path(path: &Path) -> AppResult<PathBuf> {
    let file_name = path
        .file_name()
        .ok_or_else(|| AppError::Validation("HWID path has no file name".into()))?
        .to_string_lossy();
    Ok(path.with_file_name(format!("{file_name}.{}.tmp", Uuid::new_v4())))
}

#[cfg(test)]
mod tests {
    use super::HwidStore;
    use std::fs;
    use std::io::{self, ErrorKind};
    use uuid::Uuid;

    #[test]
    fn get_or_create_is_stable_and_reset_rotates() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("device-id");
        let store = HwidStore::new(path);
        let first = store.get_or_create().unwrap();
        let second = store.get_or_create().unwrap();
        let third = store.reset().unwrap();

        assert_eq!(first, second);
        assert_ne!(first, third);
        assert_eq!(store.get_or_create().unwrap(), third);
    }

    #[test]
    fn custom_override_can_be_set_and_cleared_without_losing_auto_value() {
        let dir = tempfile::tempdir().unwrap();
        let store = HwidStore::new(dir.path().join("device-id"));
        let auto = store.get_or_create().unwrap();
        let custom = Uuid::new_v4();

        store.set_custom(Some(custom)).unwrap();
        assert_eq!(store.get_or_create().unwrap(), custom);
        let described = store.describe().unwrap();
        assert_eq!(described.auto, Some(auto));
        assert_eq!(described.custom, Some(custom));
        assert_eq!(described.effective, custom);

        store.set_custom(None).unwrap();
        assert_eq!(store.get_or_create().unwrap(), auto);
        assert_eq!(store.describe().unwrap().custom, None);
    }

    #[test]
    fn reset_preserves_custom_override_and_rotates_auto_value() {
        let dir = tempfile::tempdir().unwrap();
        let store = HwidStore::new(dir.path().join("device-id"));
        let old_auto = store.get_or_create().unwrap();
        let custom = Uuid::new_v4();
        store.set_custom(Some(custom)).unwrap();

        let new_auto = store.reset().unwrap();
        let described = store.describe().unwrap();
        assert_ne!(old_auto, new_auto);
        assert_eq!(described.auto, Some(new_auto));
        assert_eq!(described.custom, Some(custom));
        assert_eq!(described.effective, custom);
    }

    #[test]
    fn reads_legacy_raw_uuid_and_migrates_on_write() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("device-id");
        let legacy = Uuid::new_v4();
        fs::write(&path, legacy.to_string()).unwrap();
        let store = HwidStore::new(path.clone());

        assert_eq!(store.get_or_create().unwrap(), legacy);
        store.set_custom(Some(Uuid::new_v4())).unwrap();
        assert!(fs::read_to_string(path)
            .unwrap()
            .trim_start()
            .starts_with('{'));
    }

    #[test]
    fn failed_reset_preserves_previous_hwid_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("device-id");
        let store = HwidStore::new(path.clone());
        let previous = store.get_or_create().unwrap();
        let previous_bytes = fs::read(&path).unwrap();

        let result = store.reset_with_replace(|_, _| {
            Err(io::Error::new(
                ErrorKind::PermissionDenied,
                "forced replacement failure",
            ))
        });

        assert!(result.is_err());
        assert_eq!(fs::read(&path).unwrap(), previous_bytes);
        assert_eq!(store.get_or_create().unwrap(), previous);
    }

    #[test]
    fn rejects_invalid_or_non_v4_persisted_values() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("device-id");
        let store = HwidStore::new(path.clone());

        fs::write(&path, "machine-name-derived-value").unwrap();
        assert!(store.get_or_create().is_err());

        fs::write(&path, Uuid::nil().to_string()).unwrap();
        assert!(store.get_or_create().is_err());

        fs::write(&path, r#"{"auto":"00000000-0000-0000-0000-000000000000"}"#).unwrap();
        assert!(store.get_or_create().is_err());
    }
}
